bbapp/urls.py
from django.urls import path
from django.contrib.auth import views as djangoviews
from bbapp import views
from bbapp.forms import UserLoginForm
from .views import HomePageView, SearchResultsView

urlpatterns = [
    path('', views.hometemp, name='home'),
    path('messaging/', views.messaging, name='messaging'),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.createprofile, name="profile"),
    path('land/', views.hometemp, name="land"),
    path('listnew/', views.createlisting, name="newlisting"), #already linked to see new listing
    path('buyList/', views.buyList, name="buyList"),
    path('searchresults', SearchResultsView.as_view(), name = "searchresults"),
    path('search/', views.searchbooks, name = "search"),
    path('searchfilter/', views.searchbooks, name='searchfilter'),
    path('searchfilter2', views.changeOrdering, name='searchfilter2'),

    path('logout/', views.logoutuser, name='logout'),
    path('login/',djangoviews.LoginView.as_view(template_name="login.html",authentication_form=UserLoginForm),name='login'),

    path('messages/', views.createmessage, name='messages'),
    path('createtransaction/(?P<bookid>\s+)', views.createtransaction, name='createtransaction'),
    path('viewmytransactions/', views.viewmytransactions, name='viewmytransactions'),
    path('viewtransactionmessages/(?P<selleruser>\s+)(?P<buyeruser>\s+)(?P<transactionid>\s+)', views.viewtransactionmessages, name='viewtransactionmessages'),
    path('donewithtransaction/(?P<doneusername>\s+)(?P<transactionid>\s+)', views.donewithtransaction, name='donewithtransaction'),
    path('reportuser/(?P<transactionid>\s+)', views.reporteduser, name='reportuser'),
    
    path('cart/', views.viewcart, name='cart'),
    path('addtocart/(?P<bookid>\s+)', views.addtocart, name='addtocart'),
    path('addtowishlist/(?P<bookid>\s+)', views.addtowishlist, name='addtowishlist'),
    path('reportedbook/(?P<bookid>\s+)', views.reportedbook, name='reportedbook'),
    path('removefromcart/(?P<bookid>\s+)', views.removefromcart, name='removefromcart'),
    path('removefromwishlist/(?P<bookid>\s+)', views.removefromwishlist, name='removefromwishlist'),
    path('switchfromwishlisttocart/(?P<bookid>\s+)', views.switchfromwishlisttocart, name='switchfromwishlisttocart'),
    path('wishlist/', views.viewwishlist, name='wishlist'),
    path('myprofile/', views.viewmyprofile, name='myprofile'),
    path('removelisting/(?P<bookid>\s+)', views.removelisting, name='removelisting'),
    
]

bookbargains/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bbapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Sum
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
import uuid
from datetime import datetime

FIELD_CHOICES = (
    ('SO', 'Select One'),
    ('ART', 'Arts'),
    ('MSC', 'Music'),
    ('HST', 'History'),
    ('LNG', 'Languages'),
    ('LAW', 'Law'),
    ('PHL', 'Philosophy'),
    ('THE', 'Theology'),
    ('ECN', 'Economics'),
    ('PLS', 'Political Science'),
    ('PSY', 'Psychology'),
    ('SOC', 'Sociology'),
    ('NUR', 'Nursing'),
    ('BIO', 'Biology'),
    ('CHM', 'Chemistry'),
    ('PHY', 'Physics'),
    ('ENG', 'Engineering'),
    ('CSC', 'Computer Science'),
    ('MTH', 'Mathematics'),
    ('BUS', 'Business'),
    ('FIN', 'Finance'),
    ('ACT', 'Accounting'), 
    ('OTH', 'Other'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE) #User deleted? Delete profile
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length = 100, null=True)
    phone = models.CharField(max_length = 10, null=True)
    major = models.CharField(max_length = 100, null=True)
    housing = models.CharField(max_length = 100, null=True)
    field = models.CharField(
        max_length=4, choices=FIELD_CHOICES, default='Select One',
        null=True)  #dropdown
    def __str__(self):
        return self.user.username

class Rating(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    buyerrating = models.FloatField(default=5.00, )
    numberofbuyerratings = models.FloatField(default=1.00)
    sellerrating = models.FloatField(default=5.00)
    numberofsellerratings = models.FloatField(default=1.00)
    def __str__(self):
        return str(self.user.username)+' has a buyer rating of '+str(self.buyerrating)+' and a seller rating of '+str(self.sellerrating)

BOOK_CONDITION_CHOICES = (('SO', 'Select One'), ('NE', 'New'), ('GR', 'Great'),
                          ('GO', 'Good'), ('AV', 'Average'), ('PO', 'Poor'))


SELL_DONATE_CHOICES = (('SO', 'Select One'), ('SE', 'Selling'), ('DO','Donating'))

class Book(models.Model):
    uuid=models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    user = models.ForeignKey(User,default = 1,null = True, on_delete = models.SET_NULL, blank=False)
    image = models.ImageField(upload_to = 'images/', null=True, blank=False)
    selldonate = models.CharField(
        max_length=2,
        choices=SELL_DONATE_CHOICES,
        default='Select One',
        null=True)
    title = models.CharField(max_length=100, null=True)
    author = models.CharField(max_length=100, null=True)
    ISBN13 = models.CharField(max_length=13, null=True)
    ISBN13Conf = models.CharField(max_length=13, null=True)
    edition = models.CharField(max_length=100, null=True)
    condition = models.CharField(
        max_length=2,
        choices=BOOK_CONDITION_CHOICES,
        default='Select One',
        null=True)  #dropdown
    field = models.CharField(
        max_length=4, choices=FIELD_CHOICES, default='Select One',
        null=True)  #dropdown
    price = models.DecimalField(max_digits=100, decimal_places=2, null=True)
    reported = models.BooleanField(default=False)
    sold = models.BooleanField(default=False)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["price"]


TRANSACTION_CHOICES = (('Created', 'Created'), ('Pending', 'Pending'), ('Completed','Completed'))

class Transaction(models.Model):
    uuid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    buyer = models.ForeignKey(User,default = 1,null = True, on_delete = models.SET_NULL,related_name='buyer')
    seller = models.ForeignKey(User,default = 1,null = True, on_delete = models.SET_NULL, related_name='seller')
    book = models.ForeignKey(Book,default = 1,null = True, on_delete = models.SET_NULL, related_name='book')
    buyerhasrated = models.BooleanField(default=False)
    sellerhasrated = models.BooleanField(default=False)
    status = models.CharField(max_length=40, default='Created', null=True)
    # def __str__(self):
    #     return "Seller: "+str(self.seller)+", Buyer: "+str(self.buyer)+", Book: "+str(self.book.title)
    def save(self, *args, **kwargs):
        if self.buyerhasrated==False and self.sellerhasrated==False:
            self.status='Created'
        elif self.buyerhasrated or self.sellerhasrated:
            self.status='Pending'
            if self.buyerhasrated and self.sellerhasrated:
                self.status='Completed'
        super(Transaction, self).save(*args, **kwargs)

class Message(models.Model):
    text = models.TextField()
    sender = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='sender')
    recipient = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='recipient')
    transaction = models.ForeignKey(Transaction, null=True, on_delete=models.CASCADE, related_name='transaction')
    creation_time = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return 'Message: '+str(self.text)

class Cart(models.Model):
    owner = models.OneToOneField(User, on_delete = models.CASCADE, null=True)
    cartitem = models.ManyToManyField(Book)
    @property
    def total(self):
        return self.cartitem.aggregate(Sum('price'))['price__sum'] or 0
    def __str__(self):
        return 'This is the cart for: '+str(self.owner.username)

class Wishlist(models.Model):
    owner = models.OneToOneField(User, on_delete = models.CASCADE, null=True)
    item = models.ManyToManyField(Book)
    @property
    def total(self):
        return self.item.aggregate(Sum('price'))['price__sum'] or 0
    def __str__(self):
        return 'This is the wishlist for: '+str(self.owner.username)

class Reported(models.Model):
    #report_id = models.AutoField(auto_created = True, primary_key = True, null = False)
    #reporter = models.ForeignKey(User, on_delete = models.CASCADE,related_name='reporter')
    #reported = models.ForeignKey(User, on_delete = models.CASCADE, related_name='reported')
    #uuid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    reporter = models.ForeignKey(User,default = 1,null = True, on_delete = models.SET_NULL,related_name='reporter')
    reported = models.ForeignKey(User,default = 1,null = True, on_delete = models.SET_NULL, related_name='reported')
    resolved = models.BooleanField(default = False)
    reportedtransaction = models.ForeignKey(Transaction, null=True, on_delete=models.SET_NULL)
    reportedbook = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL, related_name='reportedbook')

    def __str__(self):
        return str(self.reporter)+' has reported '+str(self.reported)

templates/addrating.html
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
    <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">RATING {{rateduser.username}}</h3>
    <h6 style="color:#8a100b;">On a scale from 1-5, how would you rate the user you have done the transaction with? <br>A score of 1 would be extremely poor. A score of 5 would be perfect!</h6>
  </div>


<div class="container mt-4">
    <form method="post" class="w-75 m-auto">
      {% csrf_token %}
        {% for field in form %}
          <p id="{{ field.name }}">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <div class="text-center mt-4"><button class="text-center" type="submit">Submit Rating</button></div>
      </form>
</div>

{% endblock %}

templates/createprofile.html
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
    <h3 class="display-5 mt-4" style="color:#8a100b;">Welcome!</h3>
    <h6 style="color:#8a100b;">Thank you for creating an account! Please fill out your profile below!</h6>
  </div>


<div class="container mt-4">
    <form method="post" class="w-75 m-auto">
      {% csrf_token %}
        {% for field in p_form %}
          <p id="{{ field.name }}">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <div class="text-center mt-4"><button class="text-center" type="submit">Update Profile</button></div>
      </form>
</div>


{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block body_block %}
  <section id="clientcreation">
    <section id="inside" class="pb-3 pt-0 pb-lg-5">
        <div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
            <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">Welcome Back!</h3>
            <h6 style="color:#8a100b;">To access your own account and profile, please enter your account email and password below.</h6>
        </div>
        <div class="container" style="width: 35%;">
            <div class="mt-3 justify-content-center" id="signup">
                <form method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <p style="display: flex; align-items:center"><span class='mr-2'>Email: </span>{{form.username}}</p>
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                        <p style="display: flex; align-items:center"><span class='mr-2'>Password: </span>{{form.password}}</p>
                        {{ form.password.errors }}
                    </div>
                    <div class="text-center justify-content-center"><button type="submit">Login</button></div>
                </form>
                <!-- <form class="w-75 m-auto" method="post">
                    <div class="form-group text-left">
                        <label for="#emailsignin">Email</label>
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                            </div>
                            <input type="text" class="form-control" id="emailsignin" placeholder="Email">
                            </div>
                        <label for="#passwordsignin">Password</label>
                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-key"></i></div>
                            </div>
                            <input type="text" class="form-control" id="passwordsignin" placeholder="Password">
                        </div>
                        <div style="text-align:right;"><a href="#" class='text-muted ml-auto' style="text-decoration:underline;">Forgot Password?</a></div>
                        <div class="input-group mb-2 mr-sm-2">
                            <a onclick href='land' class="btn mx-auto mt-3" style="color: #ffffff; background-color: #8a100b;">Log In</a>
                        </div>
                    </div>
                </form> -->
            </div>
        </div>
    </section>
  </section>

{% endblock %}

templates/messages.html
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
    <h3 class="display-5 mt-4" style="color:#8a100b;">Welcome!</h3>
    <h6 style="color:#8a100b;">Create a new message.</h6>
  </div>


<div class="container mt-4">
    <form method="post" class="w-75 m-auto">
      {% csrf_token %}
        {% for field in MessageForm %}
          <p id="{{ field.name }}">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <div class="text-center mt-4"><button class="text-center" type="submit">Create Messages</button></div>
      </form>
</div>


{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
  <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">BOOKS TO BUY</h3>
  <h5 class="mb-0" style="color:#8a100b;">Browse the selection of books that are currently available. <br>If you would like to refine your selection, search for a keyword in the search bar below.</h5>
  <form action="{% url 'searchresults' %}" method="get">
    <input class="text-center my-3" name="q" type="text" placeholder="Search...">
  </form>
  {% if user.is_authenticated %} <h6 style="color:#8a100b;">If you would like to add the book to your cart, select <i class="fa fa-cart-plus"></i>. If you would like to add the book to your wishlist for later reference, select <i class="fa fa-bookmark"></i>. <br>If you feel threatened or harrassed by a post or user, select <i class="fa fa-flag"></i> to report.</h6> {% endif %}
</div>

<center>
<div class="row">

  {% for Book in object_list %}
  <div class="pt-4 col-sm-3">
      <div class="card bg-light" style="width: 18rem;">
        <img class=“card-img-top w-100" style="height:286px;width:286px;" src="{{Book.image.url}}" alt="img" >
        <div class="card-body p-3">
          <h5 class="card-title mb-0">{{Book.title}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item py-2">Field: {{Book.get_field_display}} </li>
          <li class="list-group-item py-2">Author: {{Book.author}} </li>
          <li class="list-group-item py-2">Edition: {{Book.edition}}</li>
          <li class="list-group-item py-2">ISBN: {{Book.ISBN13}} </li>
          <li class="list-group-item py-2">Condition: {{Book.get_condition_display}}</li>
          <li class="list-group-item py-2">Price: ${{Book.price}}</li>
        </ul>
        {% if user.is_authenticated %}
        <div class="card-footer">
          <a href="/messaging" class="btn btn-outline-dark" style="margin-bottom: 2px;">Message Seller</a>
        </div>
        <div class="card-footer">
          <a href="{% url 'addtocart' bookid=Book.uuid %}" class="btn btn-outline-dark "><i class="fa fa-cart-plus"></i></a>
          <a href="{% url 'addtowishlist' bookid=Book.uuid %}" class="btn btn-outline-dark"><i class="fa fa-bookmark"></i></a>
          <a href="{% url 'reportedbook' bookid=Book.uuid %}" class="btn btn-outline-danger"><i class="fa fa-flag"></i></a>
        </div>
        {% endif %}
    </div>
    <div><p></p></div>
  </div>
  {% endfor %}

</div>
<center>

{% endblock %}

templates/searchfilter.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
  <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">BOOKS TO BUY</h3>
  <h5 class="mb-0" style="color:#8a100b;">Browse the selection of books that are currently available.</h5>
  {% if user.is_authenticated %} <h6 class="mt-2" style="color:#8a100b;">
    If you would like to add the book to your cart, select <i class="fa fa-cart-plus"></i>. Once at cart, you will have the option to message the owner. <br>If you would like to add the book to your wishlist for later reference, select <i class="fa fa-bookmark"></i>. <br>If you feel threatened or harrassed by a post or user, select <i class="fa fa-flag"></i> to report.</h6> 
  {% endif %}
</div>

<div class="container bg-light rounded mt-3">
  <h5 class="text-center mb-0 pt-3 mb-2" style="color: #8a100b; font-family: 'Oswald', sans-serif; ">SEARCH BAR</h5>
  <form method="get" class="pb-3 text-center">
      <div>{{filter.form}}</div>
      <a class="btn btn-outline-dark" href="{% url 'searchfilter' %}">See All Available</a>
      <button class="btn btn-outline-dark" type="submit">Search</button>
  </form>
</div>

<center>
<button class="btn mx-auto mt-3" style="color: #fff; background-color: #8a100b;">
  <a href = '/searchfilter2' style="color:#fff">Sort by Price: High to Low</a></button>
<center>

<center>
  <div class="row">
    {% for Book in books  %}
      {% if Book.user == request.user %} <!--Hide the user's own books from them-->
      {% else %}
        {% if not Book.reported %}
          {% if not Book.sold %}
          <div class="pt-4 col-sm-3">
              <div class="card bg-light" style="width: 18rem;">
                <img class=“card-img-top w-100" style="height:286px;width:286px;" src="{{Book.image.url}}" alt="img" >
                <div class="card-body p-3">
                  <h5 class="card-title mb-0">{{Book.title}}</h5>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item py-2">Field: {{Book.get_field_display}} </li>
                  <li class="list-group-item py-2">Author: {{Book.author}} </li>
                  <li class="list-group-item py-2">Edition: {{Book.edition}}</li>
                  <li class="list-group-item py-2">ISBN: {{Book.ISBN13}} </li>
                  <li class="list-group-item py-2">Condition: {{Book.get_condition_display}}</li>
                  <li class="list-group-item py-2">Price: ${{Book.price}}</li>
                </ul>
                {% if user.is_authenticated %}
                <div class="card-footer">
                  <a href="{% url 'addtocart' bookid=Book.uuid %}" class="btn btn-outline-dark "><i class="fa fa-cart-plus"></i></a>
                  <a href="{% url 'addtowishlist' bookid=Book.uuid %}" class="btn btn-outline-dark"><i class="fa fa-bookmark"></i></a>
                  <a href="{% url 'reportedbook' bookid=Book.uuid %}" class="btn btn-outline-danger"><i class="fa fa-flag"></i></a>
                </div>
                {% endif %}
              </div>
            <div><p></p></div>
          </div>
          {% else %}
          {% endif %}
        {% endif %}
      {% endif %}
    {% endfor %}
  </div>
<center>

{% endblock %}

templates/searchresults.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
  <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">SEARCH RESULTS</h3>
  <h6 style="color:#8a100b;">Below is what our system could find for the related search. If no results are available, try a different keyword.</h6>
  {% if user.is_authenticated %} <h6 style="color:#8a100b;">If you would like to add the book to your cart, select <i class="fa fa-cart-plus"></i>. If you would like to add the book to your wishlist for later reference, select <i class="fa fa-bookmark"></i>. <br>If you feel threatened or harrassed by a post or user, select <i class="fa fa-flag"></i> to report.</h6> {% endif %}
  <form action="{% url 'searchresults' %}" method="get">
    <a style="padding-top: 3px; height: 30px;" class="btn btn-outline-dark" href="{% url 'search' %}">See All</a>
    <input class="text-center mt-2" name="q" type="text" placeholder="Search...">
  </form>
</div>


<center>
<div class="row">
  {% for Book in object_list %}
  <div class="pt-4 col-sm-3">
      <div class="card bg-light" style="width: 18rem;">
        <img class=“card-img-top w-100" style="height:286px;width:286px;" src="{{Book.image.url}}" alt="img" >
        <div class="card-body p-3">
          <h5 class="card-title mb-0">{{Book.title}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Field: {{Book.get_field_display}} </li>
          <li class="list-group-item">Author: {{Book.author}} </li>
          <li class="list-group-item">ISBN: {{Book.ISBN13}} </li>
          <li class="list-group-item">Condition: {{Book.get_condition_display}}</li>
          <li class="list-group-item">Price: ${{Book.price}}</li>
        </ul>
        {% if user.is_authenticated %}
        <div class="card-footer">
          <a href="/messaging" class="btn btn-outline-dark" style="margin-bottom: 2px;">Message Seller</a>
        </div>
        <div class="card-footer">
          <a href="{% url 'addtocart' bookid=Book.uuid %}" class="btn btn-outline-dark "><i class="fa fa-cart-plus"></i></a>
          <a href="{% url 'addtowishlist' bookid=Book.uuid %}" class="btn btn-outline-dark"><i class="fa fa-bookmark"></i></a>
          <a href="{% url 'reportedbook' bookid=Book.uuid %}" class="btn btn-outline-danger"><i class="fa fa-flag"></i></a>
        </div>
        {% endif %}
    </div>
    <div><p></p></div>
  </div>
  {% endfor %}
</div>
<center>

{% endblock %}

templates/wishlist.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron text-center pt-3 pb-0 mt-0 mb-0" style="background-color: transparent; border-radius:0px">
    <h3 class="display-5 mt-4" style="color:#8a100b; font-family: 'Oswald', sans-serif; font-size: 2em;">WISHLIST</h3>
    <h6 class="w-75 m-auto" style="color:#8a100b;">Here, you can find the items you have previously added to your wishlist. If you are interested in buying these books, please add them to your cart and complete the transaction there.</h6>
</div>

<div class="container mt-5">
    <h2></h2>
    <table class="table table-striped">
        <thead class="thead" style="color: #ffffff; background: #8a100b;">
            <tr>
                <th class="text-center" scope="col">#</th>
                <th class="text-center"></th>
                <th class="text-left" scope="col">Book</th>
                <th class="text-center" scope="col">Field</th>
                <th class="text-center" scope="col">Condition</th>
                <th class="text-center" scope="col">Price</th>
                <th class="text-center" scope="col">Options</th>
                <th class="text-center" scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for book in wishlist.item.all %}
            <tr>
              <td class="text-center align-middle" scope="row">{{ forloop.counter }}</td>
              <td class="text-center align-middle"><img style="max-height: 100px;" src="{{book.image.url}}"></td>
              <td class="text-left align-middle">
                  <div>
                    <p class="my-1">Title: {{book.title}}</p>
                    <p class="my-1">Author: {{book.author}}</p>
                    <p class="my-1">Edition: {{book.edition}}</p>
                    <p class="my-1">ISBN: {{book.ISBN13}}</p>
                  </div>
              </td>
              <td class="text-center align-middle">{{book.get_field_display}}</td>
              <td class="text-center align-middle">{{book.get_condition_display}}</td>
              <td class="text-center align-middle">${{book.price}}</td>
              <td class="text-center align-middle">
                <a href="{% url 'switchfromwishlisttocart' bookid=book.uuid %}" class="btn btn-outline-dark">Add to Cart</a>
              </td>
              <td class="text-center align-middle"><a class="btn btn-outline-dark" href="{% url 'removefromwishlist' bookid=book.uuid %}">X</a></td>
            </tr>
            {% endfor %}
            <thead class="thead" style="color: #ffffff; background: #8a100b;">
                <tr>
                    <th class="text-center" scope="col"></th>
                    <th class="text-center"></th>
                    <th class="text-left" scope="col"></th>
                    <th class="text-center" scope="col"></th>
                    <th class="text-center" scope="col"></th>
                    <th class="text-center"></th>
                    <th class="text-center" scope="col">Total</th>
                    <th class="text-center" scope="col">${{wishlist.total}}</th>
                </tr>
            </thead>

          </tbody>

    </table>
</div>

{% endblock %}